version: '3.7'
services:
  blog:
    image: blog
    container_name: personal-blog
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.msmetko.xyz`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=le"
      - "traefik.http.services.blog.loadbalancer.server.scheme=http"
      - "traefik.http.services.blog.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
    expose:
      - "3000"
    volumes:
      - "./db.sqlite3:/blog/db.sqlite3:ro"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
