version: '3'
services:
  blog:
    image: blog
    container_name: personal-blog
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./db.sqlite3:/db.sqlite3:ro"
