services:
  blog:
    image: ghcr.io/incognito124/personal-blog:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.msmetko.xyz`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=le"
      - "traefik.http.services.blog.loadbalancer.server.scheme=http"
      - "traefik.http.services.blog.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
    expose:
      - "3000"
    networks:
      - traefik_default
      - blog
  blog-db:
    image: ghcr.io/incognito124/personal-blog-db:latest
    networks:
      - blog
networks:
  traefik_default:
    external: true
  blog:
