[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.196"
sqlite = "0.33.0"

[dependencies.rocket]
version = "0.5.0"
features = ["json"]
