name: deploy on production
on:
  # Deploy only when pushed directly to the master
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh to my production server and do manual deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd personal-blog &&
            git checkout -f master &&
            git pull -f &&
            make
